"""initial

Revision ID: da0756bf03ce
Revises: 
Create Date: 2021-12-07 20:58:52.788051

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da0756bf03ce'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Suggestion',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sType', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('desc', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('User',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('password', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('PageSuggestion',
    sa.Column('suggestion', sa.Integer(), nullable=False),
    sa.Column('owner', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner'], ['User.id'], ),
    sa.ForeignKeyConstraint(['suggestion'], ['Suggestion.id'], ),
    sa.PrimaryKeyConstraint('suggestion')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('PageSuggestion')
    op.drop_table('User')
    op.drop_table('Suggestion')
    # ### end Alembic commands ###
